(title music)
(meter 3 4)
(key 0)
(composer XML2Impro-Visor.py 0.0.1)
(tempo 80.0)
(volume 127)
(bass-volume 100)
(drum-volume 100)
(chord-volume 100)
(section (style waltz))
C | G | Am | NC | G | C | G | C | F | Dm | Am | C | Dm | C | 
